-- SQL Seeds: 001_seed_job_seeker_experience.sql
-- Description: Populate sample profiles matching different states of onboarding completeness

-- 1. Insert sample finished profile (Aarav Sharma)
INSERT INTO public.profiles (
    user_id,
    full_name,
    phone,
    dob,
    gender,
    city,
    state,
    country,
    skills,
    experience,
    education,
    linkedin_url,
    github_url,
    portfolio_url,
    resume_url,
    profile_photo,
    address,
    pincode,
    edu_10th_percentage,
    edu_12th_percentage,
    edu_graduation_percentage,
    edu_university,
    edu_passing_year,
    edu_cgpa,
    exp_is_fresher,
    exp_company,
    exp_designation,
    exp_joining_date,
    exp_leaving_date,
    exp_responsibilities,
    exp_achievements,
    skills_technical,
    skills_soft,
    skills_languages,
    skills_level,
    resume_ats_score,
    resume_last_updated,
    pref_role,
    pref_industry,
    pref_city,
    pref_state,
    pref_expected_salary,
    pref_current_salary,
    pref_notice_period,
    pref_employment_type,
    pref_work_mode,
    pref_open_to_relocate,
    ach_projects,
    is_profile_wizard_completed,
    wizard_step
) VALUES (
    '00000000-0000-0000-0000-000000000001', -- Assuming seeded candidate user
    'Aarav Sharma',
    '9876543210',
    '2002-05-14',
    'Male',
    'Bengaluru',
    'Karnataka',
    'India',
    ARRAY['React', 'TypeScript', 'Node.js', 'PostgreSQL'],
    'Software Engineer at TechCorp (2024 - Present)',
    'B.Tech Computer Science from NIT Trichy (2024)',
    'https://linkedin.com/in/aaravsharma',
    'https://github.com/aaravsharma',
    'https://aaravsharma.dev',
    'https://example.com/storage/resumes/aarav_cv.pdf',
    'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    'Apartment 402, Green Glen Layout',
    '560103',
    94.50,
    91.20,
    86.40,
    'National Institute of Technology, Trichy',
    '2024',
    '8.64 / 10',
    FALSE,
    'TechCorp Software Ltd',
    'Associate Software Engineer',
    '2024-06-01',
    NULL,
    'Responsible for building high-speed React contexts, API integrations, and database tuning.',
    'Reduced front-end load latency by 25% using memoized states and virtualized lists.',
    ARRAY['React 19', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker'],
    ARRAY['Effective Communication', 'Agile Methodologies', 'Problem Solving'],
    ARRAY['English', 'Hindi', 'Kannada'],
    'Intermediate',
    88,
    '15 Jul 2026',
    'Frontend Developer',
    'IT & Software Development',
    'Bengaluru',
    'Karnataka',
    '12,00,000',
    '8,00,000',
    'Immediate',
    'Full-time',
    'Remote',
    TRUE,
    'Built decentralized voting portals using smart contracts. Restructured database index mappings.',
    TRUE,
    9
) ON CONFLICT (user_id) DO NOTHING;

-- 2. Insert sample mid-onboarding candidate (Priyan Patel - Step 3)
INSERT INTO public.profiles (
    user_id,
    full_name,
    phone,
    dob,
    gender,
    city,
    state,
    country,
    skills,
    is_profile_wizard_completed,
    wizard_step
) VALUES (
    '00000000-0000-0000-0000-000000000002',
    'Priyan Patel',
    '9123456780',
    '2003-11-22',
    'Male',
    'Ahmedabad',
    'Gujarat',
    'India',
    ARRAY[]::TEXT[],
    FALSE,
    3
) ON CONFLICT (user_id) DO NOTHING;
