-- SQL Seeds: 002_seed_employer_experience.sql
-- Description: Populate sample companies, job postings, and applications to represent professional datasets

-- 1. Insert sample completed company profile (Vercel India)
INSERT INTO public.companies (
    id,
    user_id,
    name,
    legal_name,
    logo,
    cover_image,
    gst_number,
    pan_placeholder,
    industry,
    size,
    founded_year,
    website,
    linkedin,
    facebook,
    instagram,
    twitter_x,
    head_office,
    branches,
    about,
    mission,
    vision,
    culture,
    benefits,
    office_photos,
    hiring_status,
    company_email,
    recruiter_name,
    recruiter_mobile,
    support_email,
    is_profile_complete,
    wizard_step
) VALUES (
    'e0000000-0000-0000-0000-000000000101',
    '00000000-0000-0000-0000-000000000003', -- Recruiter user ID
    'Vercel India',
    'Vercel Developer Systems India Pvt Ltd',
    '▲',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    '29AAAAA1111A1Z1',
    'ABCDE1234F',
    'Information Technology & Services',
    '501 - 1,000 Employees',
    '2015',
    'https://vercel.com',
    'https://linkedin.com/company/vercel',
    'https://facebook.com/vercel',
    'https://instagram.com/vercel',
    'https://twitter.com/vercel',
    'Bengaluru, Karnataka',
    ARRAY['Mumbai, Maharashtra', 'Gurugram, Haryana'],
    'Vercel provides the developer experience and infrastructure to build, deploy, and scale the modern web. We enable developers to host websites and web applications that deploy instantly and scale automatically.',
    'To make the web faster, more accessible, and easier to build for every developer in India and globally.',
    'A globally fast web experience where frontend development has zero operational barriers.',
    'We value speed, accessibility, and stellar UX. Our culture is remote-first, collaborative, and focused on enabling engineers to ship premium web products without friction.',
    ARRAY['Competitive Stock Options (RSUs)', 'Comprehensive Health & Wellness Coverage', 'Remote-First Workspace Reimbursements', 'Continuous Learning & Dev Budget (₹1,50,000/yr)', 'Generous Parental & Caregiver Leave'],
    ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=85', 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=600&q=85', 'https://images.unsplash.com/photo-1542744094-3a31f103e35f?auto=format&fit=crop&w=600&q=85'],
    'Active',
    'careers-india@vercel.com',
    'Shalini Roy',
    '+91 80 4912 3000',
    'support@vercel.com',
    TRUE,
    5
) ON CONFLICT (user_id) DO NOTHING;

-- 2. Insert sample jobs for Vercel India
INSERT INTO public.jobs (
    id,
    company_id,
    title,
    slug,
    category,
    location,
    country,
    salary,
    employment_type,
    experience,
    skills,
    description,
    responsibilities,
    requirements,
    benefits,
    deadline,
    is_remote,
    is_urgent,
    is_featured,
    is_hot,
    status
) VALUES (
    'j0000000-0000-0000-0000-000000000001',
    'e0000000-0000-0000-0000-000000000101',
    'Senior Frontend Engineer - Next.js',
    'senior-frontend-engineer-nextjs-vercel',
    'Tech',
    'Bengaluru, Karnataka',
    'India',
    '₹32,00,000 - ₹45,00,000 / year',
    'Full-time',
    '5 - 8 Years',
    ARRAY['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Vercel Deployments'],
    'We are seeking an expert Frontend Engineer with a deep obsession with web performance, developer experience, and design precision. You will lead development on our core enterprise Next.js application frameworks and build visual orchestration engines for developer workflows.',
    'Lead enterprise frontend architectures, optimize core web vitals, and coordinate deployment pipeline automation.',
    'BS/MS in Computer Science or equivalent, 5+ years building highly interactive Next.js web applications, mastery of rendering paradigms.',
    ARRAY['Equity RSUs', 'Full Remote Setup Budget', 'Medical Insurance', 'Performance Bonuses'],
    '2026-09-30',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    'Published'
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.jobs (
    id,
    company_id,
    title,
    slug,
    category,
    location,
    country,
    salary,
    employment_type,
    experience,
    skills,
    description,
    responsibilities,
    requirements,
    benefits,
    deadline,
    is_remote,
    is_urgent,
    is_featured,
    is_hot,
    status
) VALUES (
    'j0000000-0000-0000-0000-000000000002',
    'e0000000-0000-0000-0000-000000000101',
    'React Core Developer',
    'react-core-developer-vercel',
    'Tech',
    'Remote (India)',
    'India',
    '₹24,00,000 - ₹35,00,000 / year',
    'Full-time',
    '3 - 6 Years',
    ARRAY['React', 'TypeScript', 'Compiler Optimization', 'CSS Modules', 'Webpack'],
    'Join the team that helps render millions of production-grade pages daily. This role is focused on refining client-side rendering capabilities, React Server Components lifecycle integration, and building hyper-responsive components with motion animations.',
    'Improve virtual DOM reconciler efficiencies, build robust browser runtime plugins, and maintain component stability.',
    '3+ years of core React internals familiarity, deep understanding of AST, compiler concepts, and browser microtask queues.',
    ARRAY['Flexible Working Hours', 'Skill Enhancement Credits', 'Tech Reimbursement'],
    '2026-10-15',
    TRUE,
    FALSE,
    TRUE,
    FALSE,
    'Published'
) ON CONFLICT (slug) DO NOTHING;

-- 3. Insert sample job applications for Vercel India
INSERT INTO public.job_applications (
    id,
    job_id,
    applicant_name,
    applicant_email,
    applicant_phone,
    applicant_experience,
    applicant_education,
    resume_url,
    resume_skills,
    cover_letter,
    status,
    timeline,
    notes
) VALUES (
    'a0000000-0000-0000-0000-000000000001',
    'j0000000-0000-0000-0000-000000000001',
    'Arjun Mehta',
    'arjun.mehta@gmail.com',
    '+91 98765 43210',
    '6 Years',
    'B.Tech in Computer Science, IIT Bombay',
    'arjun_mehta_resume.pdf',
    ARRAY['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Webpack', 'Performance Tuning'],
    'Dear Hiring Team, I have been building full-stack React and Next.js applications for the past 5 years and have been following Vercel''s innovations closely. At my current organization, I led the migration of our customer dashboard to Next.js App Router, resulting in a 42% improvement in LCP and an overall perfect 100 lighthouse score. I am extremely excited about the prospect of bringing my performance-oriented frontend engineering expertise to the Vercel India office.',
    'Interview Scheduled',
    '[{"date": "18 Jul 2026", "status": "Applied", "description": "Application sourced via JOB Lo verification crawler"}, {"date": "18 Jul 2026", "status": "Shortlisted", "description": "Skills match threshold passed (>85% score)"}, {"date": "19 Jul 2026", "status": "Interview Scheduled", "description": "Technical Round 1 scheduled with Lead Frontend Architect"}]'::jsonb,
    ARRAY['Extremely strong performance benchmarks from previous role.', 'Knows RSC streaming lifecycle thoroughly. Highly recommended for Senior role.']
) ON CONFLICT DO NOTHING;
